### ISSUE TITLE
Restaurant name error in the dataset "MUL1382.json"

### ISSUE THREAD

**Issue by Victorwz** [budzianowski/multiwoz#46] opened 2020-11-09 08:14 UTC
In the Multi-WOZ 2.2 "data.json", line 7419586, dialog_id : MUL1382.json:
"text": "We've narrowed it down to 3.  **kihinoor**, the gandhi, and mahal of cambridge.  Would you like me to make a reservation for you?"
"text": "Yes please make a reservation for 3 people at 16:00 on Saturday at any of those choices."
"text": "I was able to book at Kohinoor for 16:00 on Saturday for 3 people.  Your reference number is NTJ52ASI.  The table will be held for 15 minutes."

Actually, in the database for restaurant domain, there is no restaurant named "kihinoor" but there is one restaurant named "kohinoor". And based on the next two utterances, I believe the first restaurant name in the first utterance should be "kohinoor".

**Comment by XiaoxueZang** [comment] 2020-11-13 04:35
Thanks for your interests in the dataset. It's a typo caused by the crowd worker. We'll correct it in the next update. Please note that MultiWOZ 2.2 didn't fix the original utterances to maintain its naturalness as typos usually happen in the daily conversation. Dialogue states are fixed in MultiWOZ 2.2 to accommodate to it.
I checked the dialogue states annotation of this dialogue. They look correct to me. Please feel free to add follow-ups if you any question.

**Closed** 2020-11-13 06:12 UTC
